language: python

matrix:
  include:
    - sudo: required
      language: python
      python: 3.6
      services:
        - docker
      env:
        CIBW_SKIP="*-manylinux1_i686"
        CIBW_MANYLINUX1_X86_64_IMAGE="quay.io/wenxiang/kafka-cffi-manylinux-builder"

install:
  - pip install twine cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - sudo chown -R $USER .
  - git status
  - docker run --rm -w /app -v $PWD:/app 
    quay.io/wenxiang/kafka-cffi-pypy-builder scripts/build-wheels.sh
  - git status
  - sudo chown -R $USER .
  - python setup.py sdist
  - ls -la wheelhouse/*.whl pypy-wheelhouse/*.whl dist/*.tar.gz
