language: python

matrix:
  include:
    - sudo: required
      language: python
      python: 3.6
      services:
        - docker
      env:
        CIBW_SKIP="*-manylinux1_i686"
        CIBW_MANYLINUX_X86_64_IMAGE="quay.io/hyperair/kafka-cffi-manylinux-builder:manylinux-upgrade"
        CIBW_MANYLINUX_PYPY_X86_64_IMAGE="quay.io/hyperair/kafka-cffi-manylinux-builder:manylinux-upgrade"

install:
  - pip install twine
  # install custom cibuildwheel branch with pypy41 abi support
  - pip install git+https://github.com/hyperair/cibuildwheel@pypy41-abi#egg=cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - sudo chown -R $(id -u):$(id -g) .
  - python setup.py sdist
  - ls -la wheelhouse/*.whl dist/*.tar.gz
  - wheel_versions=($(ls -1 wheelhouse/*.whl |
                       sed -re 's/.*kafka_cffi-([^-]+)-(pp|cp)[0-9]+.*/\1/' |
                       sort -u))
  - if [[ ${#wheel_versions[@]} -gt 1 ]]; then
      echo "Multiple wheel versions found (${wheel_versions[@]}). Aborting upload to pypi";
      false;
    elif [[ ! $(python setup.py --version) =~ dev ]]; then
      echo "Not a dev version, uploading to pypi" &&
      twine upload dist/*.tar.gz wheelhouse/*.whl pypy-wheelhouse/*.whl;
    else
      echo "Dev version, skipping upload";
    fi
